name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  OWNER: raihara3
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PASS: ${{ secrets.REDIS_PASS }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set environment
        run: echo REDIS_HOST =${{ secrets.REDIS_HOST }} >> .env.production

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: yarn run lint

      - name: Run Jest
        run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: communication-webar
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /home/runner/.cache/docker-build
          key: ${{ runner.os }}-communication-webar-docker-${{ hashFiles('Dockerfile') }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-communication-webar-docker-
      - uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - run: |
          IMAGE_PATH=ghcr.io/${OWNER}/${IMAGE_NAME}
          TAG=${GITHUB_REF##*/}
          opt=''
          [ -d /home/runner/.cache/docker-build ] && opt='--cache-from type=local,src=/home/runner/.cache/docker-build'
          docker login ghcr.io -u $OWNER -p ${{ secrets.CR_PAT }}
          docker buildx build --output type=docker,name=$IMAGE_PATH:$TAG,push=false ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
          docker push $IMAGE_PATH:$TAG

  slackNotification:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


